insert into public.exercises (
  name, muscle_group, equipment, aliases, secondary_muscles,
  movement_pattern, is_unilateral
)
values
  ('Strict Pull-Up', 'Back', 'Pull-Up Bar', array['Strict Pullup'], array['Biceps','Grip','Core'], 'vertical_pull', false),
  ('Chest-to-Bar Pull-Up', 'Back', 'Pull-Up Bar', array['Chest to Bar Pullup'], array['Biceps','Grip','Core'], 'vertical_pull', false),
  ('Kipping Pull-Up', 'Back', 'Pull-Up Bar', array['Kipping Pullup'], array['Biceps','Grip','Core','Shoulders'], 'gymnastics_skill', false),
  ('Butterfly Pull-Up', 'Back', 'Pull-Up Bar', array['Butterfly Pullup'], array['Biceps','Grip','Core','Shoulders'], 'gymnastics_skill', false),
  ('Muscle-Up', 'Full Body', 'Pull-Up Bar', array['Bar Muscle-Up'], array['Back','Chest','Triceps','Biceps','Shoulders','Grip','Core'], 'gymnastics_skill', false),
  ('Ring Muscle-Up', 'Full Body', 'Gymnastic Rings', array['Rings Muscle-Up'], array['Back','Chest','Triceps','Biceps','Shoulders','Grip','Core'], 'gymnastics_skill', false),
  ('Ring Row', 'Back', 'Gymnastic Rings', array['Bodyweight Ring Row'], array['Biceps','Rear Delts','Core'], 'horizontal_pull', false),
  ('Ring Push-Up', 'Chest', 'Gymnastic Rings', array['Rings Push-Up'], array['Triceps','Shoulders','Core'], 'horizontal_push', false),
  ('Ring Dip', 'Chest', 'Gymnastic Rings', array['Rings Dip'], array['Triceps','Shoulders','Core'], 'vertical_push', false),
  ('Korean Dip', 'Chest', 'Parallel Bars', array['Behind-the-Back Dip'], array['Triceps','Shoulders','Core'], 'vertical_push', false),
  ('Straight Bar Dip', 'Chest', 'Pull-Up Bar', array['Bar Dip'], array['Triceps','Shoulders','Core'], 'vertical_push', false),
  ('Handstand Hold', 'Shoulders', 'Bodyweight', array['Freestanding Handstand'], array['Triceps','Core','Forearms'], 'gymnastics_hold', false),
  ('Wall Handstand Hold', 'Shoulders', 'Wall', array['Wall Handstand'], array['Triceps','Core'], 'gymnastics_hold', false),
  ('Handstand Push-Up', 'Shoulders', 'Bodyweight', array['HSPU'], array['Triceps','Upper Chest','Core'], 'vertical_push', false),
  ('Wall Handstand Push-Up', 'Shoulders', 'Wall', array['Wall HSPU'], array['Triceps','Upper Chest','Core'], 'vertical_push', false),
  ('Pike Push-Up', 'Shoulders', 'Bodyweight', array['Pike Press'], array['Triceps','Upper Chest','Core'], 'vertical_push', false),
  ('Deficit Pike Push-Up', 'Shoulders', 'Parallettes', array['Elevated Pike Push-Up'], array['Triceps','Upper Chest','Core'], 'vertical_push', false),
  ('Planche Lean', 'Shoulders', 'Bodyweight', array['Planche Lean Hold'], array['Chest','Triceps','Core','Wrists'], 'gymnastics_hold', false),
  ('Tuck Planche', 'Shoulders', 'Parallettes', array['Tuck Planche Hold'], array['Chest','Triceps','Core','Wrists'], 'gymnastics_hold', false),
  ('Advanced Tuck Planche', 'Shoulders', 'Parallettes', array['Advanced Tuck Planche Hold'], array['Chest','Triceps','Core','Wrists'], 'gymnastics_hold', false),
  ('Straddle Planche', 'Shoulders', 'Parallettes', array['Straddle Planche Hold'], array['Chest','Triceps','Core','Wrists'], 'gymnastics_hold', false),
  ('Full Planche', 'Shoulders', 'Parallettes', array['Planche Hold'], array['Chest','Triceps','Core','Wrists'], 'gymnastics_hold', false),
  ('Front Lever Tuck', 'Back', 'Pull-Up Bar', array['Tuck Front Lever'], array['Lats','Core','Biceps','Grip'], 'gymnastics_hold', false),
  ('Advanced Tuck Front Lever', 'Back', 'Pull-Up Bar', array['Advanced Front Lever Tuck'], array['Lats','Core','Biceps','Grip'], 'gymnastics_hold', false),
  ('Straddle Front Lever', 'Back', 'Pull-Up Bar', array['Front Lever Straddle'], array['Lats','Core','Biceps','Grip'], 'gymnastics_hold', false),
  ('Front Lever', 'Back', 'Pull-Up Bar', array['Full Front Lever'], array['Lats','Core','Biceps','Grip'], 'gymnastics_hold', false),
  ('Front Lever Raise', 'Back', 'Pull-Up Bar', array['Front Lever Lift'], array['Lats','Core','Biceps','Grip'], 'gymnastics_skill', false),
  ('Back Lever Tuck', 'Shoulders', 'Gymnastic Rings', array['Tuck Back Lever'], array['Chest','Back','Core','Biceps'], 'gymnastics_hold', false),
  ('Back Lever', 'Shoulders', 'Gymnastic Rings', array['Full Back Lever'], array['Chest','Back','Core','Biceps'], 'gymnastics_hold', false),
  ('L-Sit', 'Core', 'Parallettes', array['L Sit Hold'], array['Hip Flexors','Triceps','Shoulders'], 'gymnastics_hold', false),
  ('V-Sit', 'Core', 'Parallettes', array['V Sit Hold'], array['Hip Flexors','Triceps','Shoulders'], 'gymnastics_hold', false),
  ('Tuck Sit', 'Core', 'Parallettes', array['Tuck Support Hold'], array['Hip Flexors','Triceps','Shoulders'], 'gymnastics_hold', false),
  ('Hollow Body Hold', 'Core', 'Bodyweight', array['Hollow Hold'], array['Hip Flexors'], 'gymnastics_hold', false),
  ('Arch Body Hold', 'Posterior Chain', 'Bodyweight', array['Superman Arch Hold'], array['Glutes','Back','Hamstrings'], 'gymnastics_hold', false),
  ('Dragon Flag', 'Core', 'Bench', array['Dragon Flag Raise'], array['Hip Flexors','Lats'], 'gymnastics_skill', false),
  ('Toes-to-Bar', 'Core', 'Pull-Up Bar', array['Toes to Bar'], array['Hip Flexors','Grip','Lats'], 'gymnastics_skill', false),
  ('Knees-to-Elbows', 'Core', 'Pull-Up Bar', array['Knees to Elbows'], array['Hip Flexors','Grip','Lats'], 'gymnastics_skill', false),
  ('Skin the Cat', 'Shoulders', 'Gymnastic Rings', array['Skin-the-Cat'], array['Back','Chest','Biceps','Core'], 'gymnastics_skill', false),
  ('German Hang', 'Shoulders', 'Gymnastic Rings', array['Ring German Hang'], array['Chest','Biceps','Back'], 'gymnastics_hold', false),
  ('Support Hold', 'Triceps', 'Gymnastic Rings', array['Ring Support Hold'], array['Shoulders','Chest','Core'], 'gymnastics_hold', false),
  ('False Grip Hang', 'Grip', 'Gymnastic Rings', array['Ring False Grip Hang'], array['Forearms','Biceps','Back'], 'grip_support', false),
  ('One-Arm Push-Up', 'Chest', 'Bodyweight', array['Single-Arm Push-Up'], array['Triceps','Shoulders','Core'], 'horizontal_push', true),
  ('Archer Push-Up', 'Chest', 'Bodyweight', array['Archer Press-Up'], array['Triceps','Shoulders','Core'], 'horizontal_push', true),
  ('Pseudo Planche Push-Up', 'Chest', 'Bodyweight', array['Planche Lean Push-Up'], array['Shoulders','Triceps','Core','Wrists'], 'horizontal_push', false),
  ('Typewriter Pull-Up', 'Back', 'Pull-Up Bar', array['Typewriter Pullup'], array['Biceps','Grip','Core'], 'vertical_pull', true),
  ('Archer Pull-Up', 'Back', 'Pull-Up Bar', array['Archer Pullup'], array['Biceps','Grip','Core'], 'vertical_pull', true),
  ('One-Arm Pull-Up', 'Back', 'Pull-Up Bar', array['Single-Arm Pull-Up'], array['Biceps','Grip','Core'], 'vertical_pull', true),
  ('One-Arm Chin-Up', 'Back', 'Pull-Up Bar', array['Single-Arm Chin-Up'], array['Biceps','Grip','Core'], 'vertical_pull', true),
  ('Pistol Squat to Box', 'Quadriceps', 'Plyo Box', array['Box Pistol Squat'], array['Glutes','Hamstrings','Core'], 'squat', true),
  ('Shrimp Squat', 'Quadriceps', 'Bodyweight', array['Single-Leg Shrimp Squat'], array['Glutes','Hamstrings','Core'], 'squat', true),
  ('Cossack Squat', 'Adductors', 'Bodyweight', array['Side-to-Side Cossack Squat'], array['Quadriceps','Glutes','Hamstrings'], 'lunge', true),
  ('Nordic Curl Eccentric', 'Hamstrings', 'Bodyweight', array['Nordic Negative'], array['Glutes'], 'isolation', false),
  ('Reverse Nordic Curl', 'Quadriceps', 'Bodyweight', array['Reverse Nordic'], array['Hip Flexors','Core'], 'isolation', false)
on conflict (lower(name))
where owner_id is null
do update set
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  aliases = excluded.aliases,
  secondary_muscles = excluded.secondary_muscles,
  movement_pattern = excluded.movement_pattern,
  is_unilateral = excluded.is_unilateral;
