insert into public.exercises (
  name,
  muscle_group,
  equipment,
  aliases,
  secondary_muscles,
  movement_pattern,
  is_unilateral
)
values
  ('Barbell Row', 'Back', 'Barbell', array['Bent-Over Barbell Row'], array['Biceps', 'Rear Delts'], 'horizontal_pull', false),
  ('Pendlay Row', 'Back', 'Barbell', array['Dead-Stop Barbell Row'], array['Biceps', 'Rear Delts'], 'horizontal_pull', false),
  ('Single-Arm Dumbbell Row', 'Back', 'Dumbbell', array['One-Arm Dumbbell Row'], array['Biceps', 'Rear Delts'], 'horizontal_pull', true),
  ('Chest-Supported Dumbbell Row', 'Back', 'Dumbbell', array['Incline Bench Dumbbell Row'], array['Biceps', 'Rear Delts'], 'horizontal_pull', false),
  ('T-Bar Row', 'Back', 'T-Bar', array['T Bar Row'], array['Biceps', 'Rear Delts'], 'horizontal_pull', false),
  ('Seated Cable Row', 'Back', 'Cable', array['Cable Row'], array['Biceps', 'Rear Delts'], 'horizontal_pull', false),
  ('Wide-Grip Seated Cable Row', 'Back', 'Cable', array['Wide Cable Row'], array['Rear Delts', 'Biceps'], 'horizontal_pull', false),
  ('Machine Row', 'Back', 'Machine', array['Seated Row Machine'], array['Biceps', 'Rear Delts'], 'horizontal_pull', false),
  ('Inverted Row', 'Back', 'Bodyweight', array['Body Row', 'Australian Pull-Up'], array['Biceps', 'Rear Delts', 'Core'], 'horizontal_pull', false),
  ('Meadows Row', 'Back', 'Landmine', array['Landmine Row'], array['Biceps', 'Rear Delts'], 'horizontal_pull', true),
  ('Seal Row', 'Back', 'Barbell', array['Bench-Supported Barbell Row'], array['Biceps', 'Rear Delts'], 'horizontal_pull', false),
  ('Pull-Up', 'Back', 'Bodyweight', array['Pullup'], array['Biceps', 'Rear Delts'], 'vertical_pull', false),
  ('Chin-Up', 'Back', 'Bodyweight', array['Chinup', 'Supinated Pull-Up'], array['Biceps'], 'vertical_pull', false),
  ('Neutral-Grip Pull-Up', 'Back', 'Bodyweight', array['Parallel-Grip Pull-Up'], array['Biceps'], 'vertical_pull', false),
  ('Lat Pulldown', 'Back', 'Cable', array['Cable Pulldown'], array['Biceps'], 'vertical_pull', false),
  ('Wide-Grip Lat Pulldown', 'Back', 'Cable', array['Wide Pulldown'], array['Biceps'], 'vertical_pull', false),
  ('Close-Grip Lat Pulldown', 'Back', 'Cable', array['Narrow-Grip Pulldown'], array['Biceps'], 'vertical_pull', false),
  ('Single-Arm Lat Pulldown', 'Back', 'Cable', array['One-Arm Lat Pulldown'], array['Biceps'], 'vertical_pull', true),
  ('Straight-Arm Pulldown', 'Back', 'Cable', array['Cable Straight-Arm Pulldown'], array['Triceps'], 'isolation', false),
  ('Dumbbell Pullover', 'Back', 'Dumbbell', array['Dumbbell Lat Pullover'], array['Chest', 'Triceps'], 'isolation', false),
  ('Cable Pullover', 'Back', 'Cable', array['Straight-Arm Cable Pullover'], array['Triceps'], 'isolation', false),
  ('Face Pull', 'Shoulders', 'Cable', array['Rope Face Pull'], array['Rear Delts', 'Upper Back'], 'horizontal_pull', false),
  ('Reverse Dumbbell Fly', 'Shoulders', 'Dumbbell', array['Rear Delt Fly'], array['Upper Back'], 'isolation', false),
  ('Reverse Pec Deck', 'Shoulders', 'Machine', array['Rear Delt Machine Fly'], array['Upper Back'], 'isolation', false),
  ('Barbell Shrug', 'Traps', 'Barbell', array['Barbell Shoulder Shrug'], array['Forearms'], 'isolation', false),
  ('Dumbbell Shrug', 'Traps', 'Dumbbell', array['Dumbbell Shoulder Shrug'], array['Forearms'], 'isolation', false),
  ('Barbell Curl', 'Biceps', 'Barbell', array['Standing Barbell Curl'], array['Forearms'], 'isolation', false),
  ('Dumbbell Curl', 'Biceps', 'Dumbbell', array['Standing Dumbbell Curl'], array['Forearms'], 'isolation', false),
  ('EZ-Bar Curl', 'Biceps', 'EZ Bar', array['EZ Curl'], array['Forearms'], 'isolation', false),
  ('Hammer Curl', 'Biceps', 'Dumbbell', array['Neutral-Grip Curl'], array['Forearms', 'Brachialis'], 'isolation', false),
  ('Incline Dumbbell Curl', 'Biceps', 'Dumbbell', array['Incline Curl'], array['Forearms'], 'isolation', false),
  ('Preacher Curl', 'Biceps', 'EZ Bar', array['EZ-Bar Preacher Curl'], array['Forearms'], 'isolation', false),
  ('Cable Curl', 'Biceps', 'Cable', array['Standing Cable Curl'], array['Forearms'], 'isolation', false),
  ('Bayesian Cable Curl', 'Biceps', 'Cable', array['Behind-the-Body Cable Curl'], array['Forearms'], 'isolation', true),
  ('Concentration Curl', 'Biceps', 'Dumbbell', array['Seated Concentration Curl'], array['Forearms'], 'isolation', true),
  ('Spider Curl', 'Biceps', 'Dumbbell', array['Chest-Supported Curl'], array['Forearms'], 'isolation', false),
  ('Reverse Curl', 'Forearms', 'EZ Bar', array['Overhand Curl'], array['Biceps', 'Brachialis'], 'isolation', false),
  ('Wrist Curl', 'Forearms', 'Dumbbell', array['Dumbbell Wrist Curl'], array[]::text[], 'isolation', false),
  ('Reverse Wrist Curl', 'Forearms', 'Dumbbell', array['Wrist Extension'], array[]::text[], 'isolation', false),
  ('Farmer Carry', 'Grip', 'Dumbbell', array['Farmers Walk', 'Farmer Walk'], array['Traps', 'Core', 'Forearms'], 'carry', false)
on conflict (lower(name))
where owner_id is null
do update set
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  aliases = excluded.aliases,
  secondary_muscles = excluded.secondary_muscles,
  movement_pattern = excluded.movement_pattern,
  is_unilateral = excluded.is_unilateral;
