insert into public.exercises (
  name, muscle_group, equipment, aliases, secondary_muscles,
  movement_pattern, is_unilateral
)
values
  ('Band Pull-Apart', 'Shoulders', 'Resistance Band', array['Resistance Band Pull Apart'], array['Rear Delts','Upper Back'], 'prehab', false),
  ('Band External Rotation', 'Shoulders', 'Resistance Band', array['Shoulder External Rotation'], array['Rotator Cuff'], 'prehab', true),
  ('Cable External Rotation', 'Shoulders', 'Cable', array['Cable Shoulder External Rotation'], array['Rotator Cuff'], 'prehab', true),
  ('Side-Lying External Rotation', 'Shoulders', 'Dumbbell', array['Side Lying Shoulder External Rotation'], array['Rotator Cuff'], 'prehab', true),
  ('Band Internal Rotation', 'Shoulders', 'Resistance Band', array['Shoulder Internal Rotation'], array['Rotator Cuff'], 'prehab', true),
  ('Scapular Push-Up', 'Shoulders', 'Bodyweight', array['Push-Up Plus','Scap Push-Up'], array['Serratus','Chest'], 'prehab', false),
  ('Scapular Pull-Up', 'Back', 'Pull-Up Bar', array['Scap Pull-Up'], array['Lats','Lower Traps','Grip'], 'prehab', false),
  ('Wall Slide', 'Shoulders', 'Wall', array['Shoulder Wall Slide'], array['Serratus','Upper Back'], 'mobility', false),
  ('Wall Angel', 'Shoulders', 'Wall', array['Wall Angels'], array['Upper Back','Rotator Cuff'], 'mobility', false),
  ('Serratus Wall Slide', 'Shoulders', 'Resistance Band', array['Banded Serratus Wall Slide'], array['Serratus','Upper Back'], 'prehab', false),
  ('Prone Y Raise', 'Shoulders', 'Bodyweight', array['Prone Y'], array['Lower Traps','Rotator Cuff'], 'prehab', false),
  ('Prone T Raise', 'Shoulders', 'Bodyweight', array['Prone T'], array['Rear Delts','Upper Back'], 'prehab', false),
  ('Prone W Raise', 'Shoulders', 'Bodyweight', array['Prone W'], array['Rotator Cuff','Upper Back'], 'prehab', false),
  ('Shoulder CAR', 'Shoulders', 'Bodyweight', array['Shoulder Controlled Articular Rotation'], array['Rotator Cuff'], 'mobility', true),
  ('Thoracic Rotation', 'Upper Back', 'Bodyweight', array['Open Book Rotation'], array['Core','Shoulders'], 'mobility', true),
  ('Quadruped Thoracic Rotation', 'Upper Back', 'Bodyweight', array['Thread the Needle'], array['Shoulders','Core'], 'mobility', true),
  ('Thoracic Extension on Foam Roller', 'Upper Back', 'Foam Roller', array['Foam Roller Thoracic Extension'], array['Shoulders'], 'mobility', false),
  ('Cat-Cow', 'Back', 'Bodyweight', array['Cat Cow Stretch'], array['Core'], 'mobility', false),
  ('Child Pose Lat Stretch', 'Back', 'Bodyweight', array['Childs Pose Lat Stretch'], array['Shoulders'], 'mobility', false),
  ('90/90 Hip Switch', 'Hips', 'Bodyweight', array['90 90 Hip Rotation'], array['Glutes','Adductors'], 'mobility', false),
  ('90/90 Hip Stretch', 'Hips', 'Bodyweight', array['90 90 Stretch'], array['Glutes'], 'mobility', true),
  ('Hip CAR', 'Hips', 'Bodyweight', array['Hip Controlled Articular Rotation'], array['Glutes','Core'], 'mobility', true),
  ('Hip Flexor Stretch', 'Hips', 'Bodyweight', array['Half-Kneeling Hip Flexor Stretch'], array['Quadriceps'], 'mobility', true),
  ('Couch Stretch', 'Quadriceps', 'Bench', array['Rear Foot Elevated Hip Flexor Stretch'], array['Hip Flexors'], 'mobility', true),
  ('Adductor Rockback', 'Adductors', 'Bodyweight', array['Adductor Rock Back'], array['Hips'], 'mobility', true),
  ('Frog Stretch', 'Adductors', 'Bodyweight', array['Frog Hip Stretch'], array['Hips'], 'mobility', false),
  ('Cossack Mobility Squat', 'Adductors', 'Bodyweight', array['Cossack Mobility'], array['Hips','Quadriceps','Hamstrings'], 'mobility', true),
  ('Ankle Dorsiflexion Mobilization', 'Calves', 'Bodyweight', array['Knee to Wall Ankle Mobilization'], array['Ankles'], 'mobility', true),
  ('Soleus Stretch', 'Calves', 'Bodyweight', array['Bent Knee Calf Stretch'], array['Ankles'], 'mobility', true),
  ('Straight-Knee Calf Stretch', 'Calves', 'Bodyweight', array['Gastrocnemius Stretch'], array['Ankles'], 'mobility', true),
  ('Banded Ankle Mobilization', 'Calves', 'Resistance Band', array['Banded Ankle Dorsiflexion'], array['Ankles'], 'mobility', true),
  ('Short Foot Exercise', 'Feet', 'Bodyweight', array['Foot Doming','Arch Doming'], array['Ankles'], 'prehab', true),
  ('Toe Yoga', 'Feet', 'Bodyweight', array['Toe Control Drill'], array['Ankles'], 'prehab', true),
  ('Single-Leg Balance', 'Full Body', 'Bodyweight', array['Single Leg Balance Hold'], array['Feet','Ankles','Glutes','Core'], 'balance', true),
  ('Copenhagen Plank', 'Adductors', 'Bench', array['Copenhagen Side Plank'], array['Core','Obliques','Hips'], 'prehab', true),
  ('Side-Lying Hip Abduction', 'Glutes', 'Bodyweight', array['Side Lying Leg Raise'], array['Hips'], 'prehab', true),
  ('Clamshell', 'Glutes', 'Resistance Band', array['Banded Clamshell'], array['Hips'], 'prehab', true),
  ('Lateral Band Walk', 'Glutes', 'Resistance Band', array['Monster Walk Sideways'], array['Hips'], 'prehab', false),
  ('Monster Walk', 'Glutes', 'Resistance Band', array['Banded Monster Walk'], array['Hips'], 'prehab', false),
  ('Terminal Knee Extension', 'Quadriceps', 'Resistance Band', array['TKE','Banded Knee Extension'], array['Knees'], 'prehab', true),
  ('Spanish Squat', 'Quadriceps', 'Resistance Band', array['Spanish Squat Hold'], array['Knees','Glutes'], 'prehab', false),
  ('Step-Down', 'Quadriceps', 'Plyo Box', array['Controlled Step Down'], array['Glutes','Knees'], 'prehab', true),
  ('Peterson Step-Up', 'Quadriceps', 'Plyo Box', array['Peterson Step'], array['Glutes','Calves','Knees'], 'prehab', true),
  ('Single-Leg Glute Bridge', 'Glutes', 'Bodyweight', array['One Leg Glute Bridge'], array['Hamstrings','Core'], 'prehab', true),
  ('Hamstring Walkout', 'Hamstrings', 'Bodyweight', array['Bridge Walkout'], array['Glutes','Core'], 'prehab', false),
  ('Heel-Elevated Tibialis Raise', 'Tibialis', 'Bodyweight', array['Wall Tibialis Raise'], array['Ankles'], 'prehab', false),
  ('Banded Inversion', 'Ankles', 'Resistance Band', array['Ankle Inversion Band'], array['Calves'], 'prehab', true),
  ('Banded Eversion', 'Ankles', 'Resistance Band', array['Ankle Eversion Band'], array['Calves'], 'prehab', true),
  ('Dead Bug Heel Tap', 'Core', 'Bodyweight', array['Heel Tap Dead Bug'], array['Hip Flexors'], 'prehab', true),
  ('Bird Dog Row', 'Core', 'Dumbbell', array['Quadruped Bird Dog Row'], array['Back','Glutes','Shoulders'], 'prehab', true),
  ('McGill Curl-Up', 'Core', 'Bodyweight', array['McGill Curl Up'], array[]::text[], 'prehab', true),
  ('Side Plank', 'Core', 'Bodyweight', array['Lateral Plank'], array['Obliques','Shoulders','Glutes'], 'isometric', true),
  ('Pallof Hold', 'Core', 'Cable', array['Anti-Rotation Hold'], array['Obliques','Shoulders'], 'prehab', true)
on conflict (lower(name))
where owner_id is null
do update set
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  aliases = excluded.aliases,
  secondary_muscles = excluded.secondary_muscles,
  movement_pattern = excluded.movement_pattern,
  is_unilateral = excluded.is_unilateral;
