insert into public.exercises (
  name,
  muscle_group,
  equipment,
  aliases,
  secondary_muscles,
  movement_pattern,
  is_unilateral
)
values
  ('Back Squat', 'Quadriceps', 'Barbell', array['Barbell Back Squat'], array['Glutes', 'Hamstrings', 'Core'], 'squat', false),
  ('Front Squat', 'Quadriceps', 'Barbell', array['Barbell Front Squat'], array['Glutes', 'Core'], 'squat', false),
  ('Goblet Squat', 'Quadriceps', 'Dumbbell', array['Dumbbell Goblet Squat'], array['Glutes', 'Core'], 'squat', false),
  ('Hack Squat', 'Quadriceps', 'Machine', array['Hack Squat Machine'], array['Glutes', 'Hamstrings'], 'squat', false),
  ('Smith Machine Squat', 'Quadriceps', 'Smith Machine', array['Smith Squat'], array['Glutes', 'Hamstrings'], 'squat', false),
  ('Box Squat', 'Quadriceps', 'Barbell', array['Barbell Box Squat'], array['Glutes', 'Hamstrings', 'Core'], 'squat', false),
  ('Zercher Squat', 'Quadriceps', 'Barbell', array['Barbell Zercher Squat'], array['Glutes', 'Upper Back', 'Core'], 'squat', false),
  ('Overhead Squat', 'Quadriceps', 'Barbell', array['Barbell Overhead Squat'], array['Glutes', 'Shoulders', 'Core'], 'squat', false),
  ('Leg Press', 'Quadriceps', 'Machine', array['Machine Leg Press'], array['Glutes', 'Hamstrings'], 'squat', false),
  ('Single-Leg Press', 'Quadriceps', 'Machine', array['One-Leg Press'], array['Glutes', 'Hamstrings'], 'squat', true),
  ('Leg Extension', 'Quadriceps', 'Machine', array['Machine Leg Extension'], array[]::text[], 'isolation', false),
  ('Sissy Squat', 'Quadriceps', 'Bodyweight', array['Bodyweight Sissy Squat'], array['Core'], 'squat', false),
  ('Wall Sit', 'Quadriceps', 'Bodyweight', array['Wall Squat Hold'], array['Glutes'], 'isolation', false),
  ('Deadlift', 'Posterior Chain', 'Barbell', array['Conventional Deadlift'], array['Glutes', 'Hamstrings', 'Back', 'Core'], 'hinge', false),
  ('Trap-Bar Deadlift', 'Posterior Chain', 'Trap Bar', array['Hex-Bar Deadlift'], array['Glutes', 'Hamstrings', 'Quadriceps', 'Back'], 'hinge', false),
  ('Sumo Deadlift', 'Posterior Chain', 'Barbell', array['Wide-Stance Deadlift'], array['Glutes', 'Hamstrings', 'Quadriceps'], 'hinge', false),
  ('Romanian Deadlift', 'Hamstrings', 'Barbell', array['RDL'], array['Glutes', 'Back'], 'hinge', false),
  ('Dumbbell Romanian Deadlift', 'Hamstrings', 'Dumbbell', array['Dumbbell RDL'], array['Glutes', 'Back'], 'hinge', false),
  ('Single-Leg Romanian Deadlift', 'Hamstrings', 'Dumbbell', array['Single-Leg RDL'], array['Glutes', 'Core'], 'hinge', true),
  ('Good Morning', 'Hamstrings', 'Barbell', array['Barbell Good Morning'], array['Glutes', 'Back'], 'hinge', false),
  ('Cable Pull-Through', 'Glutes', 'Cable', array['Pull-Through'], array['Hamstrings'], 'hinge', false),
  ('Back Extension', 'Posterior Chain', 'Bodyweight', array['Hyperextension'], array['Glutes', 'Hamstrings', 'Back'], 'hinge', false),
  ('Barbell Hip Thrust', 'Glutes', 'Barbell', array['Hip Thrust'], array['Hamstrings'], 'hinge', false),
  ('Glute Bridge', 'Glutes', 'Bodyweight', array['Floor Glute Bridge'], array['Hamstrings'], 'hinge', false),
  ('Cable Glute Kickback', 'Glutes', 'Cable', array['Cable Kickback'], array['Hamstrings'], 'isolation', true),
  ('Hip Abduction Machine', 'Glutes', 'Machine', array['Machine Hip Abduction'], array[]::text[], 'isolation', false),
  ('Hip Adduction Machine', 'Adductors', 'Machine', array['Machine Hip Adduction'], array[]::text[], 'isolation', false),
  ('Bulgarian Split Squat', 'Quadriceps', 'Dumbbell', array['Rear-Foot-Elevated Split Squat', 'RFESS'], array['Glutes', 'Hamstrings'], 'lunge', true),
  ('Walking Lunge', 'Quadriceps', 'Dumbbell', array['Dumbbell Walking Lunge'], array['Glutes', 'Hamstrings'], 'lunge', true),
  ('Reverse Lunge', 'Quadriceps', 'Dumbbell', array['Backward Lunge'], array['Glutes', 'Hamstrings'], 'lunge', true),
  ('Forward Lunge', 'Quadriceps', 'Dumbbell', array['Dumbbell Forward Lunge'], array['Glutes', 'Hamstrings'], 'lunge', true),
  ('Lateral Lunge', 'Adductors', 'Dumbbell', array['Side Lunge'], array['Quadriceps', 'Glutes'], 'lunge', true),
  ('Step-Up', 'Quadriceps', 'Dumbbell', array['Dumbbell Step-Up'], array['Glutes', 'Hamstrings'], 'lunge', true),
  ('Pistol Squat', 'Quadriceps', 'Bodyweight', array['Single-Leg Squat'], array['Glutes', 'Hamstrings', 'Core'], 'squat', true),
  ('Lying Leg Curl', 'Hamstrings', 'Machine', array['Lying Hamstring Curl'], array[]::text[], 'isolation', false),
  ('Seated Leg Curl', 'Hamstrings', 'Machine', array['Seated Hamstring Curl'], array[]::text[], 'isolation', false),
  ('Nordic Hamstring Curl', 'Hamstrings', 'Bodyweight', array['Nordic Curl'], array['Glutes'], 'isolation', false),
  ('Glute-Ham Raise', 'Hamstrings', 'Machine', array['GHR'], array['Glutes', 'Back'], 'hinge', false),
  ('Standing Calf Raise', 'Calves', 'Machine', array['Calf Raise'], array[]::text[], 'isolation', false),
  ('Seated Calf Raise', 'Calves', 'Machine', array['Seated Machine Calf Raise'], array[]::text[], 'isolation', false),
  ('Leg Press Calf Raise', 'Calves', 'Machine', array['Calf Press'], array[]::text[], 'isolation', false),
  ('Tibialis Raise', 'Tibialis', 'Bodyweight', array['Toe Raise'], array[]::text[], 'isolation', false)
on conflict (lower(name))
where owner_id is null
do update set
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  aliases = excluded.aliases,
  secondary_muscles = excluded.secondary_muscles,
  movement_pattern = excluded.movement_pattern,
  is_unilateral = excluded.is_unilateral;
