insert into public.exercises (
  name, muscle_group, equipment, aliases, secondary_muscles,
  movement_pattern, is_unilateral
)
values
  ('A-Skip', 'Full Body', 'Bodyweight', array['A Skip Drill'], array['Hip Flexors','Calves','Hamstrings'], 'sprint_drill', true),
  ('B-Skip', 'Full Body', 'Bodyweight', array['B Skip Drill'], array['Hip Flexors','Hamstrings','Calves'], 'sprint_drill', true),
  ('Wall Sprint Drill', 'Full Body', 'Wall', array['Wall Acceleration Drill'], array['Hip Flexors','Glutes','Calves','Core'], 'sprint_drill', true),
  ('Falling Start Sprint', 'Full Body', 'Bodyweight', array['Falling Sprint Start'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sprint', false),
  ('Three-Point Start Sprint', 'Full Body', 'Bodyweight', array['3 Point Start Sprint'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sprint', false),
  ('Flying Sprint', 'Full Body', 'Bodyweight', array['Flying 10','Flying Sprint Drill'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sprint', false),
  ('Resisted Band Sprint', 'Full Body', 'Resistance Band', array['Band Resisted Sprint'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sprint', false),
  ('Sled Sprint', 'Full Body', 'Sled', array['Resisted Sled Sprint'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sprint', false),
  ('Hill Sprint', 'Full Body', 'Bodyweight', array['Uphill Sprint'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sprint', false),
  ('Pro Agility Shuttle', 'Full Body', 'Cones', array['5-10-5 Shuttle','Pro Shuttle'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'change_of_direction', true),
  ('Three-Cone Drill', 'Full Body', 'Cones', array['L Drill','3 Cone Drill'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'change_of_direction', true),
  ('T-Drill', 'Full Body', 'Cones', array['T Test Agility Drill'], array['Glutes','Quadriceps','Calves'], 'change_of_direction', true),
  ('Illinois Agility Drill', 'Full Body', 'Cones', array['Illinois Agility Test'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'change_of_direction', true),
  ('Lateral Shuffle Drill', 'Full Body', 'Cones', array['Defensive Shuffle'], array['Glutes','Adductors','Quadriceps','Calves'], 'change_of_direction', true),
  ('Carioca Drill', 'Full Body', 'Cones', array['Grapevine Drill'], array['Glutes','Adductors','Core','Calves'], 'change_of_direction', true),
  ('Backpedal to Sprint', 'Full Body', 'Cones', array['Backpedal Sprint Transition'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'change_of_direction', false),
  ('Sprint to Deceleration', 'Full Body', 'Cones', array['Sprint Stop Drill','Deceleration Drill'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'deceleration', false),
  ('Lateral Deceleration Drill', 'Full Body', 'Cones', array['Lateral Stick Drill'], array['Glutes','Adductors','Quadriceps','Calves'], 'deceleration', true),
  ('Single-Leg Hop and Stick', 'Full Body', 'Bodyweight', array['Single Leg Hop Stick'], array['Glutes','Quadriceps','Hamstrings','Calves'], 'deceleration', true),
  ('Lateral Bound and Stick', 'Full Body', 'Bodyweight', array['Skater Bound Stick'], array['Glutes','Adductors','Quadriceps','Calves'], 'deceleration', true),
  ('Reactive Cone Shuffle', 'Full Body', 'Cones', array['Reactive Agility Shuffle'], array['Glutes','Quadriceps','Calves'], 'reactive_agility', true),
  ('Mirror Agility Drill', 'Full Body', 'Cones', array['Partner Mirror Drill'], array['Glutes','Quadriceps','Calves'], 'reactive_agility', true),
  ('Reactive Sprint Start', 'Full Body', 'Bodyweight', array['Reaction Sprint'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'reactive_agility', false),
  ('Approach Jump', 'Full Body', 'Bodyweight', array['Running Vertical Jump'], array['Quadriceps','Glutes','Calves','Core'], 'jump', false),
  ('Single-Leg Approach Jump', 'Full Body', 'Bodyweight', array['One Leg Approach Jump'], array['Quadriceps','Glutes','Calves','Core'], 'jump', true),
  ('Repeated Vertical Jump', 'Full Body', 'Bodyweight', array['Continuous Vertical Jumps'], array['Quadriceps','Glutes','Calves'], 'jump', false),
  ('Medicine Ball Soccer Throw', 'Full Body', 'Medicine Ball', array['Overhead Soccer Throw'], array['Shoulders','Back','Core','Triceps'], 'ballistic_throw', false),
  ('Medicine Ball Sprint Start Throw', 'Full Body', 'Medicine Ball', array['Med Ball Acceleration Throw'], array['Glutes','Core','Shoulders','Triceps'], 'ballistic_throw', false),
  ('Medicine Ball Step-Behind Rotational Throw', 'Full Body', 'Medicine Ball', array['Step Behind Med Ball Throw'], array['Obliques','Glutes','Shoulders','Core'], 'ballistic_throw', true),
  ('Medicine Ball Shotput Shuffle', 'Full Body', 'Medicine Ball', array['Shuffle Shot Put Throw'], array['Chest','Shoulders','Triceps','Core','Glutes'], 'ballistic_throw', true),
  ('Baseball Rotational Throw', 'Full Body', 'Medicine Ball', array['Baseball Med Ball Throw'], array['Obliques','Glutes','Shoulders','Core'], 'sport_power', true),
  ('Pitcher Step-Behind Throw', 'Full Body', 'Medicine Ball', array['Pitching Med Ball Step Behind'], array['Shoulders','Core','Glutes','Obliques'], 'sport_power', true),
  ('Tennis Rotational Throw', 'Full Body', 'Medicine Ball', array['Tennis Med Ball Rotation'], array['Obliques','Glutes','Shoulders','Core'], 'sport_power', true),
  ('Golf Rotational Throw', 'Full Body', 'Medicine Ball', array['Golf Med Ball Rotation'], array['Obliques','Glutes','Shoulders','Core'], 'sport_power', true),
  ('Hockey Rotational Throw', 'Full Body', 'Medicine Ball', array['Hockey Med Ball Rotation'], array['Obliques','Glutes','Shoulders','Core'], 'sport_power', true),
  ('Football Lineman Get-Off', 'Full Body', 'Bodyweight', array['Lineman Stance Start'], array['Glutes','Quadriceps','Hamstrings','Calves'], 'sport_power', false),
  ('Football Lateral Break Drill', 'Full Body', 'Cones', array['DB Break Drill','Defensive Back Break'], array['Glutes','Quadriceps','Calves'], 'change_of_direction', true),
  ('Basketball Defensive Slide', 'Full Body', 'Cones', array['Basketball Slide Drill'], array['Glutes','Adductors','Quadriceps','Calves'], 'change_of_direction', true),
  ('Basketball Closeout Drill', 'Full Body', 'Cones', array['Defensive Closeout'], array['Glutes','Quadriceps','Calves','Core'], 'deceleration', true),
  ('Volleyball Block Jump', 'Full Body', 'Bodyweight', array['Block Jump Drill'], array['Quadriceps','Glutes','Calves','Shoulders'], 'sport_power', false),
  ('Volleyball Approach Jump', 'Full Body', 'Bodyweight', array['Spike Approach Jump'], array['Quadriceps','Glutes','Calves','Core'], 'sport_power', false),
  ('Soccer Lateral Cut Drill', 'Full Body', 'Cones', array['Soccer Cutting Drill'], array['Glutes','Adductors','Quadriceps','Calves'], 'change_of_direction', true),
  ('Soccer Acceleration Drill', 'Full Body', 'Cones', array['Soccer First Step Acceleration'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sprint', false),
  ('Hockey Lateral Bound', 'Full Body', 'Slide Board', array['Skater Power Bound'], array['Glutes','Adductors','Quadriceps','Calves'], 'sport_power', true),
  ('Slide Board Lateral Stride', 'Full Body', 'Slide Board', array['Slide Board Skater'], array['Glutes','Adductors','Quadriceps','Core'], 'sport_endurance', true),
  ('Combat Sprawl', 'Full Body', 'Bodyweight', array['Wrestling Sprawl','MMA Sprawl'], array['Chest','Shoulders','Core','Glutes','Quadriceps'], 'sport_power', false),
  ('Wrestler Stance Motion Drill', 'Full Body', 'Bodyweight', array['Wrestling Stance Movement'], array['Quadriceps','Glutes','Core','Calves'], 'sport_endurance', true),
  ('Boxing Footwork Shuffle', 'Full Body', 'Bodyweight', array['Boxing Footwork Drill'], array['Calves','Glutes','Core'], 'sport_endurance', true),
  ('Lateral Tennis Shuffle', 'Full Body', 'Cones', array['Tennis Court Shuffle'], array['Glutes','Adductors','Quadriceps','Calves'], 'change_of_direction', true),
  ('Court Suicide Sprint', 'Full Body', 'Cones', array['Suicides','Line Sprint'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'conditioning', false),
  ('Repeated Sprint Shuttle', 'Full Body', 'Cones', array['Repeated Shuttle Sprint'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sport_endurance', false),
  ('Tempo Run', 'Full Body', 'Bodyweight', array['Tempo Running'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'conditioning', false),
  ('Stride Run', 'Full Body', 'Bodyweight', array['Running Strides'], array['Glutes','Hamstrings','Quadriceps','Calves'], 'sprint_drill', false)
on conflict (lower(name))
where owner_id is null
do update set
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  aliases = excluded.aliases,
  secondary_muscles = excluded.secondary_muscles,
  movement_pattern = excluded.movement_pattern,
  is_unilateral = excluded.is_unilateral;
